### ISSUE TITLE
About the top percent in setting 1, replay dataset. 

### ISSUE THREAD

**Issue by glorgao** [ryanxhr/DWBC#1]
Hi haoran, 

I find there might exists a confusing setting in get_dataset.py, line 116:

```
# select top 20% return trajectories
inds_all = np.argsort(return_traj)[::-1]
succ_num = int(len(inds_all) * 0.05)
```

should I replace 0.05 to 0.2 for running experiments with top 20% trajectories ?

**Comment by ryanxhr** [comment]
Hi cheng,

Sorry for the confusion, there's no need to replace 0.05 to 0.2. In setting 2, we set the top 5% high return trajectories as well-performing trajectories and sample every Xth trajectories from them to constitute De.

**Comment by ryanxhr** [comment]
Hi cheng,

Sorry for the confusion, there's no need to replace 0.05 to 0.2. In setting 2, we set the top 5% high return trajectories as well-performing trajectories and sample every Xth trajectories from them to constitute De.

**Comment by glorgao** [comment]
Thank you very much! 

by the way, I found DWBC very robust and very fast, thanks for sharing.

**Comment by ryanxhr** [comment]
It's my pleasure, thanks!
